### ISSUE TITLE
Refactor Create Checkout Endpoint

### ISSUE THREAD

**Issue by NickArakaki** [aA-Hackathon-Team-9/hackathon_team9#71]
Should accept "is_bar" from request and filter for roles based on "is_bar" and calculate tipouts for those roles

**Comment by taylorcornwall766** [comment]
@NickArakaki is this still active?

**Comment by NickArakaki** [comment]
Yes, we might want to refactor depending on the implementation the client wants

**Comment by bchoi28** [comment]
- [x] ensure POST and GET endpoint for checkouts returns same structure in response body (POST response body contains "breakdown" key; GET response body contains "checkout_tipout_breakdowns" key)
